
dist: bionic

services:
  - docker

language: bash

if: tag IS present

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
  matrix:
    - IMAGE=haproxy
    - IMAGE=webcam
    - IMAGE=octoprint

stages:
  - name: test
    if: tag IS present OR branch = master
  - name: push
    if: tag IS present OR branch = master

cache:
  directories:
  - docker_images

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --privileged linuxkit/binfmt:v0.7
  - docker buildx create --use
  - docker buildx build
    --platform $PLATFORMS
    --build-arg "VERSION=$TRAVIS_BRANCH"
    --tag maddogjt/dockto-$IMAGE:$TRAVIS_BRANCH
    `if [ -n "$TRAVIS_TAG" ]; then echo "--tag maddogjt/dockto-$IMAGE:latest"; fi`
    --push
    $IMAGE
