before_install:
  - curl -sf https://test.docker.com | sh
  - docker --version

dist: bionic

language: bash

if: tag IS present

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
  matrix:
    - IMAGE=haproxy
    - IMAGE=webcam
    - IMAGE=octoprint

stages:
  - name: test
    if: tag IS present OR branch = master
  - name: push
    if: tag IS present OR branch = master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --privileged linuxkit/binfmt:v0.7
  - docker buildx create --use
  - docker buildx build
    --platform $PLATFORMS
    --build-arg "VERSION=$TRAVIS_BRANCH"
    --tag maddogjt/dockto-$IMAGE:$TRAVIS_BRANCH
    `if [ -n "$TRAVIS_TAG" ]; then echo "--tag maddogjt/dockto-$IMAGE:latest"; fi`
    --push
    $IMAGE
