version: '3'
services:
  octoprint:
    image: maddogjt/dockto-octoprint
    build: 
      context: octoprint/
      args:
        - VERSION=1.4.0
    volumes:
      - ${CONFIG}/octoprint:/config
    devices:
      - ${PRINTER_DEVICE}:/dev/printer
    restart: always
    networks:
      dockto:
    expose:
      - "5000"

  webcam:
    image: maddogjt/dockto-webcam
    build: 
      context: webcam/
    environment:
      - MJPEG_STREAMER_INPUT
      - MJPEG_STREAMER_OUTPUT
    restart: always
    devices:
      - /dev/vchiq
      - /dev/vcsm
    networks:
      dockto:
    expose:
      - "8080"

  haproxy:
    image: maddogjt/dockto-haproxy
    build: 
      context: haproxy/
    environment:
      - HTTP_PORT
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    networks:
      dockto:


# Custom network so all services can communicate using a FQDN
networks:
    dockto: